# Generated by Django 5.0.6 on 2024-07-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_options_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
