# Generated by Django 5.0.6 on 2024-07-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='keys_file',
            field=models.FileField(blank=True, null=True, upload_to='keys/', verbose_name='Файл с ключами'),
        ),
    ]
