version: '3.8'

volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:13.0-alpine
    container_name: playtopia-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  playtopia:
    build: ./playtopia
    container_name: playtopia-backend
    env_file: .env
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    depends_on:
      - db
    ports:
      - 8000:8000
    restart: always
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py collectstatic --noinput &&
                    gunicorn playtopia.wsgi:application --bind 0.0.0.0:8000 &&
                    stripe listen --forward-to localhost:8000/payment/stripe-webhook/"

  redis:
    image: redis:alpine
    restart: unless-stopped

  celery:
    build: ./playtopia
    container_name: playtopia-celery
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - static_data:/app/static
    restart: always
    command: celery -A playtopia worker -l info

  nginx:
    build: ./nginx
    container_name: playtopia-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - 80:80
    restart: always
