# Generated by Django 5.0.6 on 2024-07-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='users\\default_user.png', upload_to='users/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
