# Generated by Django 5.0.6 on 2024-07-03 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_reviews_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='Ключ')),
                ('status', models.IntegerField(choices=[(1, 'Выдан'), (0, 'Не выдан')], default=0, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Игра')),
            ],
        ),
    ]
