# Generated by Django 5.0.6 on 2024-07-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_activationkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationKey',
        ),
    ]
