# Generated by Django 5.0.6 on 2024-07-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_activationkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не опубликован'), (1, 'Опубликован')], default=0, verbose_name='Статус'),
        ),
    ]
