# Generated by Django 5.0.6 on 2024-07-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_review_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-time_create']},
        ),
    ]
