# Generated by Django 5.0.6 on 2024-07-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='games\\default.png', upload_to='games/', verbose_name='Обложка'),
        ),
    ]
